extern unsigned short g_wLCDX;
extern unsigned short g_wLCDY;
extern unsigned short g_wLCDYAuto;
extern unsigned short g_bSetDataXor;
extern unsigned short g_bFormatRealFillBlank;
extern void LCDInit(void);
extern void LCDOpen(void);
extern void LCDClose(void);
extern void LCDClear(void);
extern void LCDCursorON(void);
extern void LCDCursorOFF(void);
extern void LCDCursorClear(void);
extern void LCDSetCursorPosX(unsigned short wCursorPosX,unsigned short wCursorWidth);
extern void LCDSetCursorPosY(unsigned short wCursorPosY,unsigned short wCursorHeight);
extern void LCDDrawPoint(unsigned short wPosX,unsigned short wPosY);
extern void LCDDrawBKLine(unsigned short wY,unsigned short wX1,unsigned short wX2);
extern void LCDDrawHLine(unsigned short wY,unsigned short wX1,unsigned short wX2);
extern void LCDDrawVLine(unsigned short wX,unsigned short wY1,unsigned short wY2);
extern void LCDDrawXLine(unsigned short wX1,unsigned short wY1,unsigned short wX2,unsigned short wY2);
extern void LCDDrawHLineDot(unsigned short wY,unsigned short wX1,unsigned short wX2);
extern void LCDDrawVLineDot(unsigned short wX,unsigned short wY1,unsigned short wY2);
extern void LCDDrawRect(unsigned short wX1,unsigned short wY1,unsigned short wX2,unsigned short wY2);
extern void LCDDrawCircle(unsigned short wX0,unsigned short wY0,unsigned short wR);
extern void LCDImageOut(unsigned short wPosX,unsigned short wPosY,unsigned short wCX,unsigned short wCY,unsigned short* pData);
extern void LCDTextOut(unsigned short wPosX,unsigned short wPosY,char* pszText);
extern void LCDAsciiOut(unsigned short wPosX,unsigned short wPosY,char* pszText);
extern void LCDTimeOut(unsigned short wPosX,unsigned short wPosY,unsigned short wHour,unsigned short wMinute,unsigned short wSecond,unsigned short wMilliSecond);
extern void LCDDateOut(unsigned short wPosX,unsigned short wPosY,unsigned short wYear,unsigned short wMonth,unsigned short wDay);
extern void LCDByteOut(unsigned short wPosX,unsigned short wPosY,unsigned short wData,unsigned short wFormat);
extern void LCDWordOut(unsigned short wPosX,unsigned short wPosY,unsigned short wData);
extern void LCDRealOut(unsigned short wPosX,unsigned short wPosY,unsigned long fData,unsigned short wFormat);
extern void FormatReal(char* pszText,unsigned long dwData,unsigned short wFormat);
extern void AutoLCDAsciiOut(char* pszText);
extern void AutoLCDTextOut(char* pszText);
extern void AutoLCDByteOut(unsigned short wData,unsigned short wFormat);
extern void AutoLCDWordOut(unsigned short wData);
extern void AutoLCDRealOut(unsigned long fData,unsigned short wFormat);
extern void AutoLCDOutERR_OK(unsigned short bERR);
extern void AutoLCDOutALM_OK(unsigned short bALM);
extern void AutoLCDOutYES_NO(unsigned short bYES);
extern void AutoLCDOutOFF_ON(unsigned short bOFF);
extern void AutoLCDOut__1__0(unsigned short b__1);


extern void LCDFill(unsigned char Data);
extern void LCDDisplay(rom unsigned char *p);
