#ifndef CMYHMIDMRUNIT_H
#define CMYHMIDMRUNIT_H

enum IndexAnalog
{
	_INDEX_ANALOG = INDEX_ANALOG
	,INDEX_1Ia
	,INDEX_1Ib
	,INDEX_1Ic
	,INDEX_1Ua
	,INDEX_1Ub
	,INDEX_1Uc
	,INDEX_1Uab
	,INDEX_1Ubc
	,INDEX_1Uca
	,INDEX_1P
	,INDEX_1Q
	,INDEX_2P
	,INDEX_2Q
	,INDEX_PF
	,INDEX_2Ia
	,INDEX_2Ib
	,INDEX_2Ic
	,INDEX_2IA
	,INDEX_2IB
	,INDEX_2IC
	,INDEX_2Ua
	,INDEX_2Ub
	,INDEX_2Uc
	,INDEX_2Uab
	,INDEX_2Ubc
	,INDEX_2Uca
	,INDEX_23I0
	,INDEX_23I2
	,INDEX_23U0
	,INDEX_23U2
	,INDEX_F
	,INDEX_2Ix
	,INDEX_2Uxab
	,INDEX_2Uxbc
	,INDEX_2Uxca
	,INDEX_23Ux2
	,INDEX_Fx
	,INDEX_PhI
	,INDEX_QhI
	,INDEX_PhE
	,INDEX_QhE
	,INDEX_PE1
	,INDEX_PE2
	,INDEX_PE3
	,INDEX_PE4
};

enum IndexParamUnit
{
	_INDEX_PARAM_UNIT = INDEX_PARAM_RESERVED
	,INDEX_PARAM_ALARMKM
	,INDEX_PARAM_ALARMCLOSE
	,INDEX_PARAM_ALARMOPEN
	,INDEX_PARAM_ALARMCT
	,INDEX_PARAM_ALARMPT
	,INDEX_PARAM_MODECTM
	,INDEX_PARAM_MODECTP
	,INDEX_PARAM_MODEPT
	,INDEX_PARAM_SCALECT
	,INDEX_PARAM_SCALEPT
	,INDEX_PARAM_LINKINPE1
	,INDEX_PARAM_LINKINPE2
	,INDEX_PARAM_LINKINPE3
	,INDEX_PARAM_LINKINPE4
	,INDEX_PARAM_PULSESPERKWH1
	,INDEX_PARAM_PULSESPERKWH2
	,INDEX_PARAM_PULSESPERKWH3
	,INDEX_PARAM_PULSESPERKWH4
};

enum IndexParamScale2
{
	_INDEX_PARAM_SCALE2 = INDEX_PARAM_SCALE2
	,INDEX_PARAM_SCALE2IM
	,INDEX_PARAM_SCALE2IP
	,INDEX_PARAM_SCALE2ULN
	,INDEX_PARAM_SCALE23I0
	,INDEX_PARAM_SCALE23U0
	,INDEX_PARAM_SCALE2IX
	,INDEX_PARAM_SCALE2UX
};

enum IndexAlarmed
{
	_INDEX_ALARMED = INDEX_ALARMED
	,INDEX_ALARMED_CTM
	,INDEX_ALARMED_CTP
	,INDEX_ALARMED_CT
	,INDEX_ALARMED_PT
	,INDEX_ALARMED_KM
	,INDEX_ALARMED_CLOSE
	,INDEX_ALARMED_OPEN
	,INDEX_ALARMED_ERRORCLOSE
	,INDEX_ALARMED_ERROROPEN
	,INDEX_ALARMED_ENABLELOCAL
	,INDEX_ALARMED_ENABLEREMOTE
	,INDEX_ALARMED_DIRECTP
	,INDEX_ALARMED_DIRECTQ
	,INDEX_ALARMED_LOCKCLOSE
};

enum IndexBOInfo
{
	_INDEX_BOINFO = INDEX_BOINFO
	,INDEX_BOINFO_COUNTCLOSE
	,INDEX_BOINFO_TIMECLOSEMIN
	,INDEX_BOINFO_TIMECLOSEAVG
	,INDEX_BOINFO_TIMECLOSEMAX
	,INDEX_BOINFO_COUNTOPEN
	,INDEX_BOINFO_TIMEOPENMIN
	,INDEX_BOINFO_TIMEOPENAVG
	,INDEX_BOINFO_TIMEOPENMAX
	,INDEX_BOINFO_TRIPIMAX
	,INDEX_BOINFO_TRIPI2TSUM
};

#ifndef LOCKCOUNT
#define LOCKCOUNT			6 // 5s
#endif

#ifndef LOCKRELEASE
#define LOCKRELEASE			60 // 600ms ±ØÐë´óÓÚ50
#endif

//-----------------------------------------------------------------------------
#undef CLASSNAME_HMI
#define CLASSNAME_HMI CMyHMIDMRUnit
class CMyHMIDMRUnit:public CMyHMIDMR
{
public:
	WORD m_wLockCnt;
	WORD m_wLockRelease;
	BOOL m_bLockRelease;
public:
	void OnInit(void);
	void OnTimer10ms(void);
public:
	char* GetEventText(EVENT* pEvent);
	void GetProtectActDataInfo(WORD wProtectAct,WORD wProtectIndexExt,WORD wActData,PROTECTACTDATAINFO* pProtectActDataInfo);
	void AutoLCDDataOut(WORD wIndex);
	void GetEditMetrics(WORD* pData);
	void TestLights(void);
protected:
	VIRTUAL void iiiOnWhileLoopExt(WORD wKeyCode);
	friend class CMyHMI;
	friend class CMyHMIDMR;
};


extern CMyOutput g_lightEnableLocal;
extern CMyOutput g_lightEnableRemote;

#endif/*CMYHMIDMRUNIT_H*/


